name: TestsExample

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  uv-example:
    name: python
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          # Install a specific version of uv.
          version: "0.8.17"

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          # Download the pinned python version
          python-version-file: ".python-version"

      - name: Run tests
        run: uv run pytest
